# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoAnnotator2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from imageMonitor import SourceMonitor


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 797)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dialogFrm = QtWidgets.QFrame(self.centralwidget)
        self.dialogFrm.setMaximumSize(QtCore.QSize(223, 16777215))
        self.dialogFrm.setFrameShape(QtWidgets.QFrame.Box)
        self.dialogFrm.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dialogFrm.setLineWidth(1)
        self.dialogFrm.setObjectName("dialogFrm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dialogFrm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fileBtn = QtWidgets.QPushButton(self.dialogFrm)
        self.fileBtn.setObjectName("fileBtn")
        self.verticalLayout_3.addWidget(self.fileBtn)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.dialogFrm)
        self.workFrm = QtWidgets.QFrame(self.centralwidget)
        self.workFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.workFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workFrm.setObjectName("workFrm")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.workFrm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sourceMonitorFrm = QtWidgets.QFrame(self.workFrm)
        self.sourceMonitorFrm.setAutoFillBackground(False)
        self.sourceMonitorFrm.setFrameShape(QtWidgets.QFrame.Box)
        self.sourceMonitorFrm.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sourceMonitorFrm.setLineWidth(1)
        self.sourceMonitorFrm.setMidLineWidth(0)
        self.sourceMonitorFrm.setObjectName("sourceMonitorFrm")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sourceMonitorFrm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sourceMonitor = SourceMonitor(self.sourceMonitorFrm)
        self.sourceMonitor.setObjectName("sourceMonitor")
        self.verticalLayout.addWidget(self.sourceMonitor)
        self.verticalLayout_2.addWidget(self.sourceMonitorFrm)
        self.editorFrm = QtWidgets.QFrame(self.workFrm)
        self.editorFrm.setMinimumSize(QtCore.QSize(300, 100))
        self.editorFrm.setFrameShape(QtWidgets.QFrame.Box)
        self.editorFrm.setFrameShadow(QtWidgets.QFrame.Plain)
        self.editorFrm.setLineWidth(1)
        self.editorFrm.setObjectName("editorFrm")
        self.verticalLayout_2.addWidget(self.editorFrm)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.workFrm)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileBtn.setText(_translate("MainWindow", "Open File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
