# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoAnnotator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from imageMonitor import SourceMonitor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 797)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dialogFrm = QtWidgets.QFrame(self.centralwidget)
        self.dialogFrm.setMaximumSize(QtCore.QSize(223, 16777215))
        self.dialogFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dialogFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dialogFrm.setObjectName("dialogFrm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dialogFrm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fileBtn = QtWidgets.QPushButton(self.dialogFrm)
        self.fileBtn.setObjectName("fileBtn")
        self.verticalLayout_3.addWidget(self.fileBtn)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.dialogFrm)
        self.workFrm = QtWidgets.QFrame(self.centralwidget)
        self.workFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.workFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.workFrm.setObjectName("workFrm")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.workFrm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.monitorFrm = QtWidgets.QFrame(self.workFrm)
        self.monitorFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.monitorFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.monitorFrm.setObjectName("monitorFrm")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.monitorFrm)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fileLbl = QtWidgets.QLabel(self.monitorFrm)
        self.fileLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.fileLbl.setObjectName("fileLbl")
        self.verticalLayout_4.addWidget(self.fileLbl)
        self.QVideo = QtWidgets.QGraphicsView(self.monitorFrm)
        self.QVideo.setMinimumSize(QtCore.QSize(360, 240))
        self.QVideo.setObjectName("QVideo")
        self.verticalLayout_4.addWidget(self.QVideo)
        self.ScrollFrm = QtWidgets.QFrame(self.monitorFrm)
        self.ScrollFrm.setMinimumSize(QtCore.QSize(0, 30))
        self.ScrollFrm.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ScrollFrm.setObjectName("ScrollFrm")
        self.verticalLayout_4.addWidget(self.ScrollFrm)
        self.buttonFrm = QtWidgets.QFrame(self.monitorFrm)
        self.buttonFrm.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonFrm.setMaximumSize(QtCore.QSize(16777215, 40))
        self.buttonFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrm.setObjectName("buttonFrm")
        self.verticalLayout_4.addWidget(self.buttonFrm)
        self.verticalLayout_2.addWidget(self.monitorFrm)
        self.editorFrm = QtWidgets.QFrame(self.workFrm)
        self.editorFrm.setMinimumSize(QtCore.QSize(300, 100))
        self.editorFrm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editorFrm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editorFrm.setObjectName("editorFrm")
        self.verticalLayout_2.addWidget(self.editorFrm)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.workFrm)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileBtn.setText(_translate("MainWindow", "Open File"))
        self.fileLbl.setText(_translate("MainWindow", "Filename Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
